config/routes.rb
Rails.application.routes.draw do
  resources :posts

  delete '/posts/:id/' => 'posts#destroy', as: 'destroy_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
      
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to post_path(@post.id)
  end

  def show

  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def set_post
      @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for (@post) do |f| %>
 タイトル
<%= f.text_field :title, class:"..." %>
 本文
<%= f.text_field :body, class:"..." %>
<%= f.submit "保存", class:"..." %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
  <p>タイトル</p>
  <span><%=link_to post.title, post_path(post.id) %></span>
<% end %>
<div><%=link_to "新規作成", new_post_path %></div>

app/views/posts/new.html.erb
<%= form_for (@post) do |f| %>
     タイトル
    <%= f.text_field :title, class: "title" %>
     本文
    <%= f.text_field :body, class: "..." %>
    <%= f.submit "保存", class: "..." %>
<% end %>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>


<%= link_to "編集", edit_post_path(@post.id), class: "btn edit-btn" %>
<%= link_to "削除", destroy_post_path(@post.id), method: :delete, class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>

<div>
    <%= link_to "topへ", posts_path, class: "btn edit-btn" %>
</div>